Update
davidIvankov/imdb_clone pull request #1
Opened 2023-06-06 08:15 UTC by davidIvankov

..

2023-06-06 16:09 UTC, gobonja requested changes
Evo imaš review, ako ti što zapne ili nije jasno slobodno se javi pa ti mogu na callu pokazati.

2023-06-06 16:09 UTC, gobonja commented on src/app/shared/dataTransforming.service.ts
file ti se zove dataTransforming.service, klasa DataTransform

- Ime mora biti isto
- ime filea mora biti kebab case (data-transform.service.ts), a ime classe camel case (DataTransformService)

2023-06-06 16:09 UTC, gobonja commented on src/app/movie/movieDetailes.model.ts
> +    transform = new DataTransform()
Angular service se ne poziva u model nego u componentama

2023-06-06 16:09 UTC, gobonja commented on src/app/movie/movieDetailes.model.ts
naziv filea mora biti kebab case

2023-06-06 16:09 UTC, gobonja commented on src/app/header/menu/menu.component.ts
> -  @Output() toggleMenu = new EventEmitter<boolean>();
nazive boolean naziva sa should ili is, u ovom slučaju shouldToggleMenu

2023-06-06 16:09 UTC, gobonja commented on src/app/shared/movies.service.ts
> +    })
u servicima nema potrebe da koristiš evente
eventi se koriste za child->parent component komunikaciju

npr. metoda setMovies treba biti getMovies koja vraća Movie[], u componenti se subscribeaš na tu metodu i onda vrijednost koju ti vrati dodaš u property componenti

2023-09-29 13:10 UTC, gobonja requested changes

2023-09-29 13:10 UTC, gobonja commented on src/app/components/movies/movies.service.ts
service stavljaj u package services

2023-09-29 13:10 UTC, gobonja commented on src/app/components/movies/movies.service.ts
> +  private moviesList: Movie[] = [];
rekli smo da ovaj servis triba biti stateless

2023-09-30 10:08 UTC, davidIvankov commented
novi pull request

2023-10-07 17:21 UTC, merged